version: '3'

services:
  crowi:
    image: bakudankun/crowi:latest
    links:
      - mongo:db
      - redis:redis
      - elasticsearch:es
    ports:
      - 80:3000

  mongo:
    image: mongo

  redis:
    image: redis:alpine

  elasticsearch:
    image: elasticsearch:2
    # プラグインのKuromojiが必要
    entrypoint:
      - bash
      - -c
      - >-
        bin/plugin list | grep -q analysis-kuromoji
        || bin/plugin install analysis-kuromoji
        && exec /docker-entrypoint.sh $$0 $$@
    command: elasticsearch
